'use client'

import { useState, useRef, useEffect } from 'react'
import { Portfolio } from '@/lib/casper'
import { generateAgentResponse, ChatMessage, AgentAction } from '@/lib/agent-chat'
import { createX402Payment, ANALYSIS_COST_CSPR, ANALYSIS_RECIPIENT } from '@/lib/x402'
import { Send } from 'lucide-react'

interface AgentChatProps {
  portfolio: Portfolio | null
  analysis: any | null
  onAnalyze: () => void
}

export const AgentChat = ({ portfolio, analysis, onAnalyze }: AgentChatProps) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'agent',
      content: 'Hello! I\'m your Casper AI Portfolio Agent 🐻✨ I can analyze your portfolio, assess risk, suggest rebalancing, and even pay for analysis via x402 micropayments. How can I help you today?',
      timestamp: new Date(),
      actions: [
        { type: 'analyze', label: 'Analyze Portfolio' },
        { type: 'explore', label: 'Learn About x402' }
      ]
    }
  ])
  const [input, setInput] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSend = async () => {
    if (!input.trim()) return

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date()
    }

    setMessages(prev => [...prev, userMsg])
    setInput('')
    setIsTyping(true)

    // Simulate agent thinking
    await new Promise(resolve => setTimeout(resolve, 800))

    const response = await generateAgentResponse(input, portfolio, analysis)

    const agentMsg: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: 'agent',
      content: response.message,
      timestamp: new Date(),
      actions: response.actions
    }

    setMessages(prev => [...prev, agentMsg])
    setIsTyping(false)
  }

  const handleAction = async (action: AgentAction) => {
    if (action.type === 'analyze') {
      onAnalyze()
      return
    }

    if (action.type === 'pay') {
      setIsTyping(true)
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      // Simulate x402 payment
      const payment = await createX402Payment(ANALYSIS_COST_CSPR, ANALYSIS_RECIPIENT, 'Portfolio AI Analysis')
      
      const paymentMsg: ChatMessage = {
        id: (Date.now() + 2).toString(),
        role: 'agent',
        content: `✅ **x402 Payment Processed**\n\n- Amount: ${payment.amount} CSPR\n- Token: ${payment.token}\n- Purpose: ${payment.purpose}\n- Status: Confirmed on Casper Testnet\n\nYour analysis is now being generated by Claude AI...`,
        timestamp: new Date(),
        actions: [{ type: 'analyze', label: 'View Analysis Results' }]
      }

      setMessages(prev => [...prev, paymentMsg])
      setIsTyping(false)
      
      // Trigger actual analysis after payment
      setTimeout(() => onAnalyze(), 1500)
      return
    }

    // Handle explore and other actions
    const response = await generateAgentResponse(action.label, portfolio, analysis)
    const exploreMsg: ChatMessage = {
      id: (Date.now() + 3).toString(),
      role: 'agent',
      content: response.message,
      timestamp: new Date(),
      actions: response.actions
    }
    setMessages(prev => [...prev, exploreMsg])
  }

  return (
    <div className="bg-surface border border-border flex flex-col h-[420px]">
      {/* Header */}
      <div className="px-4 py-3 bg-black border-b border-border">
        <div className="flex items-center gap-2">
          <span className="w-5 h-5 bg-white text-black flex items-center justify-center text-[10px] font-mono font-bold">AI</span>
          <div>
            <h3 className="text-xs font-semibold text-white">Agent</h3>
            <p className="text-[10px] font-mono text-gray-400">Online • x402</p>
          </div>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-3 space-y-3">
        {messages.map((msg) => (
          <div key={msg.id} className={`flex gap-2 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
            <div className={`w-6 h-6 flex items-center justify-center flex-shrink-0 text-[10px] font-mono font-bold ${
              msg.role === 'agent' ? 'bg-black text-white' : 'bg-surface-alt border border-border text-black'
            }`}>
              {msg.role === 'agent' ? 'AI' : 'U'}
            </div>
            <div className={`max-w-[80%] space-y-1.5 ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
              <div className={`px-3 py-2 text-sm ${
                msg.role === 'agent'
                  ? 'bg-surface-alt border border-border text-black'
                  : 'bg-black text-white'
              }`}>
                <p className="whitespace-pre-line leading-relaxed">{msg.content}</p>
              </div>
              {msg.actions && msg.actions.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {msg.actions.map((action, idx) => (
                    <button
                      key={idx}
                      onClick={() => handleAction(action)}
                      className="px-2 py-1 bg-surface border border-border text-xs font-medium text-black hover:bg-black hover:text-white transition-colors"
                    >
                      {action.label}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}
        {isTyping && (
          <div className="flex gap-2">
            <span className="w-6 h-6 bg-black text-white flex items-center justify-center text-[10px] font-mono font-bold">AI</span>
            <div className="bg-surface-alt border border-border px-3 py-2 text-xs text-muted">
              Thinking<span className="terminal-cursor">_</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-3 border-t border-border bg-surface">
        <div className="flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Ask anything..."
            className="flex-1 px-3 py-2 bg-surface-alt border border-border text-sm text-black placeholder-muted focus:outline-none focus:border-black transition-colors"
          />
          <button
            onClick={handleSend}
            className="px-3 py-2 bg-black text-white hover:bg-gray-800 transition-colors"
          >
            <Send className="w-3 h-3" />
          </button>
        </div>
      </div>
    </div>
  )
}
