'use client'

import { useState, useRef, useEffect } from 'react'
import { Portfolio } from '@/lib/casper'
import { generateAgentResponse, ChatMessage, AgentAction } from '@/lib/agent-chat'
import { createX402Payment, ANALYSIS_COST_CSPR, ANALYSIS_RECIPIENT } from '@/lib/x402'
import { Send } from 'lucide-react'

interface AgentChatProps {
  portfolio: Portfolio | null
  analysis: any | null
  onAnalyze: () => void
}

export const AgentChat = ({ portfolio, analysis, onAnalyze }: AgentChatProps) => {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'welcome',
      role: 'agent',
      content: 'Hello! I\'m your Casper AI Portfolio Agent 🐻✨ I can analyze your portfolio, assess risk, suggest rebalancing, and even pay for analysis via x402 micropayments. How can I help you today?',
      timestamp: new Date(),
      actions: [
        { type: 'analyze', label: 'Analyze Portfolio' },
        { type: 'explore', label: 'Learn About x402' }
      ]
    }
  ])
  const [input, setInput] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSend = async () => {
    if (!input.trim()) return

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date()
    }

    setMessages(prev => [...prev, userMsg])
    setInput('')
    setIsTyping(true)

    // Simulate agent thinking
    await new Promise(resolve => setTimeout(resolve, 800))

    const response = await generateAgentResponse(input, portfolio, analysis)

    const agentMsg: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: 'agent',
      content: response.message,
      timestamp: new Date(),
      actions: response.actions
    }

    setMessages(prev => [...prev, agentMsg])
    setIsTyping(false)
  }

  const handleAction = async (action: AgentAction) => {
    if (action.type === 'analyze') {
      onAnalyze()
      return
    }

    if (action.type === 'pay') {
      setIsTyping(true)
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      // Simulate x402 payment
      const payment = await createX402Payment(ANALYSIS_COST_CSPR, ANALYSIS_RECIPIENT, 'Portfolio AI Analysis')
      
      const paymentMsg: ChatMessage = {
        id: (Date.now() + 2).toString(),
        role: 'agent',
        content: `✅ **x402 Payment Processed**\n\n- Amount: ${payment.amount} CSPR\n- Token: ${payment.token}\n- Purpose: ${payment.purpose}\n- Status: Confirmed on Casper Testnet\n\nYour analysis is now being generated by Claude AI...`,
        timestamp: new Date(),
        actions: [{ type: 'analyze', label: 'View Analysis Results' }]
      }

      setMessages(prev => [...prev, paymentMsg])
      setIsTyping(false)
      
      // Trigger actual analysis after payment
      setTimeout(() => onAnalyze(), 1500)
      return
    }

    // Handle explore and other actions
    const response = await generateAgentResponse(action.label, portfolio, analysis)
    const exploreMsg: ChatMessage = {
      id: (Date.now() + 3).toString(),
      role: 'agent',
      content: response.message,
      timestamp: new Date(),
      actions: response.actions
    }
    setMessages(prev => [...prev, exploreMsg])
  }

  return (
    <div className="relative group">
      <div className="relative bg-white dark:bg-ink-900 border border-black/[0.06] dark:border-white/[0.06] rounded-xl flex flex-col h-[420px] shadow-stripe-sm">
        {/* Header */}
        <div className="px-4 py-3 bg-ink-50 dark:bg-ink-800/50 border-b border-black/[0.06] dark:border-white/[0.06] rounded-t-xl">
          <div className="flex items-center gap-2">
            <span className="w-6 h-6 bg-primary text-white flex items-center justify-center text-[10px] font-mono font-bold rounded">AI</span>
            <div>
              <h3 className="text-xs font-semibold text-ink-900 dark:text-white tracking-tight">Agent</h3>
              <p className="text-[10px] font-mono text-primary">Online • x402</p>
            </div>
          </div>
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-3 space-y-3">
          {messages.map((msg) => (
            <div key={msg.id} className={`flex gap-2 ${msg.role === 'user' ? 'flex-row-reverse' : ''}`}>
              <div className={`w-6 h-6 flex items-center justify-center flex-shrink-0 text-[10px] font-mono font-bold rounded ${
                msg.role === 'agent' ? 'bg-primary text-white' : 'bg-ink-100 dark:bg-ink-800 border border-black/[0.06] dark:border-white/[0.06] text-ink-700 dark:text-ink-300'
              }`}>
                {msg.role === 'agent' ? 'AI' : 'U'}
              </div>
              <div className={`max-w-[80%] space-y-1.5 ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                <div className={`px-3 py-2 text-sm rounded-lg ${
                  msg.role === 'agent'
                    ? 'bg-ink-50 dark:bg-ink-800/50 border border-black/[0.06] dark:border-white/[0.06] text-ink-700 dark:text-ink-300'
                    : 'bg-primary text-white'
                }`}>
                  <p className="whitespace-pre-line leading-relaxed">{msg.content}</p>
                </div>
                {msg.actions && msg.actions.length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {msg.actions.map((action, idx) => (
                      <button
                        key={idx}
                        onClick={() => handleAction(action)}
                        className="px-2 py-1 bg-ink-50 dark:bg-ink-800/50 border border-black/[0.06] dark:border-white/[0.06] text-xs font-medium text-ink-600 dark:text-ink-400 hover:bg-primary/5 hover:border-primary/20 hover:text-primary transition-all duration-300 rounded"
                      >
                        {action.label}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ))}
          {isTyping && (
            <div className="flex gap-2">
              <span className="w-6 h-6 bg-primary text-white flex items-center justify-center text-[10px] font-mono font-bold rounded">AI</span>
              <div className="bg-ink-50 dark:bg-ink-800/50 border border-black/[0.06] dark:border-white/[0.06] px-3 py-2 text-xs text-ink-400 dark:text-ink-500 rounded-lg">
                Thinking<span className="terminal-cursor">_</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="p-3 border-t border-black/[0.06] dark:border-white/[0.06] bg-ink-50 dark:bg-ink-800/50 rounded-b-xl">
          <div className="flex gap-2">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleSend()}
              placeholder="Ask anything..."
              className="flex-1 px-3 py-2 bg-white dark:bg-ink-900 border border-black/[0.06] dark:border-white/[0.06] text-sm text-ink-900 dark:text-white placeholder-ink-400 dark:placeholder-ink-600 focus:outline-none focus:border-primary/50 focus:ring-1 focus:ring-primary/20 transition-all duration-300 rounded-lg"
            />
            <button
              onClick={handleSend}
              className="px-3 py-2 bg-primary text-white hover:bg-[#5a4dff] transition-all duration-300 rounded-lg"
            >
              <Send className="w-3 h-3" />
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
